var searchData=
[
  ['calculadora_0',['Calculadora',['../md__r_e_a_d_m_e.html',1,'🧮 Calculadora'],['../namespace_calculadora.html',1,'Calculadora']]],
  ['calculadora_20estándar_1',['Calculadora estándar',['../md__r_e_a_d_m_e.html#autotoc_md9',1,'Calculadora estándar'],['../md__r_e_a_d_m_e.html#autotoc_md29',1,'Ejemplos — Calculadora estándar']]],
  ['calculadora_20estándar_2',['Usar la calculadora estándar',['../md__r_e_a_d_m_e.html#autotoc_md22',1,'']]],
  ['calculadora_20gráfica_3',['Ejemplos — Calculadora gráfica',['../md__r_e_a_d_m_e.html#autotoc_md30',1,'']]],
  ['calculadora_20gráfica_4',['Usar la calculadora gráfica',['../md__r_e_a_d_m_e.html#autotoc_md24',1,'']]],
  ['calculadora_20gráfica_20📈_5',['Calculadora gráfica 📈',['../md__r_e_a_d_m_e.html#autotoc_md10',1,'']]],
  ['calculadora_3a_3acommon_6',['Common',['../namespace_calculadora_1_1_common.html',1,'Calculadora']]],
  ['calculadora_3a_3amodels_7',['Models',['../namespace_calculadora_1_1_models.html',1,'Calculadora']]],
  ['calculadora_3a_3aviewmodels_8',['ViewModels',['../namespace_calculadora_1_1_view_models.html',1,'Calculadora']]],
  ['calculadora_3a_3aviews_9',['Views',['../namespace_calculadora_1_1_views.html',1,'Calculadora']]],
  ['calculadoragrafica_10',['CalculadoraGrafica',['../namespace_calculadora_grafica.html',1,'']]],
  ['calculate_11',['Calculate',['../class_calculadora_1_1_models_1_1_calculator_model.html#a692ba23da866e11698b7792e4e35635b',1,'Calculadora::Models::CalculatorModel']]],
  ['calculatormodel_12',['CalculatorModel',['../class_calculadora_1_1_models_1_1_calculator_model.html',1,'Calculadora::Models']]],
  ['canexecute_13',['CanExecute',['../class_calculadora_1_1_common_1_1_relay_command.html#aec31bda95000054ff01480718580d5f8',1,'Calculadora.Common.RelayCommand.CanExecute()'],['../class_calculadora_1_1_common_1_1_relay_command-1-g.html#a757adedb4745bc5df5a0622a9a336f7a',1,'Calculadora.Common.RelayCommand-1-g.CanExecute()']]],
  ['canexecutechanged_14',['CanExecuteChanged',['../class_calculadora_1_1_common_1_1_relay_command.html#a4f5c750171c67a573b5cd6aff0071c4a',1,'Calculadora.Common.RelayCommand.CanExecuteChanged'],['../class_calculadora_1_1_common_1_1_relay_command-1-g.html#aac50f32d3c0e5fb0f0d7f2cb083072c3',1,'Calculadora.Common.RelayCommand-1-g.CanExecuteChanged']]],
  ['capturas_20de_20pantalla_15',['Ejemplos de uso y capturas de pantalla',['../md__r_e_a_d_m_e.html#autotoc_md28',1,'']]],
  ['características_20principales_20✨_16',['Características principales ✨',['../md__r_e_a_d_m_e.html#autotoc_md8',1,'']]],
  ['clearcommand_17',['ClearCommand',['../class_calculadora_1_1_view_models_1_1_normal_calc_view_model.html#a7563ad8bc9dda74c51d7ca62f7605359',1,'Calculadora::ViewModels::NormalCalcViewModel']]],
  ['clonar_20el_20repositorio_18',['Paso 1 — Clonar el repositorio',['../md__r_e_a_d_m_e.html#autotoc_md14',1,'']]],
  ['color_19',['Color',['../class_calculadora_1_1_models_1_1_expression_item.html#a8b1e07f66e1c0e8e2fc6737babb2479f',1,'Calculadora::Models::ExpressionItem']]],
  ['compilar_20el_20proyecto_20',['Paso 3 — Compilar el proyecto',['../md__r_e_a_d_m_e.html#autotoc_md16',1,'']]],
  ['conclusiones_20y_20reflexiones_20💭_21',['Conclusiones y reflexiones 💭',['../md__r_e_a_d_m_e.html#autotoc_md33',1,'']]],
  ['contenidos_22',['Tabla de contenidos',['../md__r_e_a_d_m_e.html#autotoc_md2',1,'']]],
  ['createdelegate_23',['CreateDelegate',['../class_xaml_generated_namespace_1_1_generated_internal_type_helper.html#a8ec4c37e82d9f4e867e9655f4eac3a78',1,'XamlGeneratedNamespace.GeneratedInternalTypeHelper.CreateDelegate(System.Type delegateType, object target, string handler)'],['../class_xaml_generated_namespace_1_1_generated_internal_type_helper.html#a8ec4c37e82d9f4e867e9655f4eac3a78',1,'XamlGeneratedNamespace.GeneratedInternalTypeHelper.CreateDelegate(System.Type delegateType, object target, string handler)']]],
  ['createinstance_24',['CreateInstance',['../class_xaml_generated_namespace_1_1_generated_internal_type_helper.html#aefb7a98fceb9c287cef4756942f441d1',1,'XamlGeneratedNamespace.GeneratedInternalTypeHelper.CreateInstance(System.Type type, System.Globalization.CultureInfo culture)'],['../class_xaml_generated_namespace_1_1_generated_internal_type_helper.html#aefb7a98fceb9c287cef4756942f441d1',1,'XamlGeneratedNamespace.GeneratedInternalTypeHelper.CreateInstance(System.Type type, System.Globalization.CultureInfo culture)']]],
  ['currentview_25',['CurrentView',['../class_calculadora_1_1_view_models_1_1_main_view_model.html#af41d2c36ddfa9a1aea268d4fbb6c2131',1,'Calculadora::ViewModels::MainViewModel']]]
];
